# These rules are documented in the same order as Prettier options page to make maintenance easier:
# https://prettier.io/docs/en/options.html
#
# Last updated version: 2.3.2 | 22/07/2021 (DD/MM/YYYY)
printWidth: 120
# tabWidth: 2 # Default
# useTabs: false # Default
# semi: true # Default
# singleQuote: false # Default
# quoteProps: "as-needed" # Default
# jsxSingleQuote: false # Default
# trailingComma: "es5" # Default
# bracketSpacing: true # Default
# jsxBracketSameLine: false # Default
# arrowParens: "always" # Default
# rangeStart: 0 # Default
# rangeEnd: Infinity # Default
# parser: null # Default
# filepath: null # Default
# requirePragma: false # Default
# insertPragma: false # Default
# proseWrap: "preserve" # Default
# htmlWhitespaceSensitivity: "css" # Default
# vueIndentScriptAndStyle: false # Default
# endOfLine: "lf" # Default
# embeddedLanguageFormatting: "auto" # Default
