default_platform(:android)

platform :android do

  ########################--------------------------------########################
  ########################--------- SETUP LANES ----------########################
  ########################--------------------------------########################

  # Check prerequisites for build and release:
  #   - Clean the project
  #   - Run tests
  #   - Run Analyzer
  private_lane :check_prerequisites do
    # Clean
    sh("flutter", "clean")

    # Run tests
    sh("flutter", "test", "test")

    # Run Analyzer
    sh("flutter", "analyze", ".")
  end

  # Run prerequisites and builds the app
  lane :build do
    # Run prerequisites
    check_prerequisites

    # Build the app
    sh("flutter", "build", "appbundle", "--dart-define=ENV=PROD")
  end

  desc "Deploy a new version to the Google Play Internal track"
  lane :internal do
    # Run prerequisites
    check_prerequisites

    # Bumps Version Code
    android_set_version_code()

    # Build the app
    sh("flutter", "build", "appbundle", "--dart-define=ENV=PROD")

    # Gets version info
    version_info = flutter_version(
      pubspec_location: "../pubspec.yaml",
    )

    # Upload the app to Play console
    supply(
      track: "internal",
      json_key_data: ENV["GOOGLE_SERVICE_ACCOUNT"],
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      version_name: version_info["version_name"],
      version_code: android_get_version_code(),
      aab: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end
end
