name: "[Firebase] Release"

on:
  release:
    types:
      - published

env:
  node_version: "14.x"
  java_version: "12.x"

jobs:
  firebase-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firebase
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      - name: Setup
        run: npm run setup-ci

      - name: Setup Environment
        run: npm run functions:fetch-env -- --token ${{ secrets.FIREBASE_CLI_TOKEN }}

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Deploy
        run: npm run deploy -- --token "${{ secrets.FIREBASE_CLI_TOKEN }}" -f
